### PR TITLE
MVP

### PR DESCRIPTION
**Pull request by arunabenji29**

### CODE REVIEW

**Comment by arunabenji29** [comment]
@lennamau : save movie functionality working

**Comment by arunabenji29** [comment]
@lennamau : 
saved movie list into Links

**Comment by arunabenji29** [comment]
@lennamau : converted Links to NavLinks

**Comment by lennamau** [comment]
React-Router-Movies

## MVP
- [x] Add 2 routes, 1 for MovieList, 1 for a specific Movie
- [x] Make the card a link to a specific URL 
- [x] Make Home button navigate to home

## Stretch
- [x] MovieCard component (DRY)
- [x] Add Save Movie functionality
- [x] Link Save Movie list
- [x] Change Links into NavLinks

## What Looks Great
- Great work MVP and part of Stretch complete
- Code is well formatted and easy to read
- Good job with frequent commits and descriptive messages

## Rating (1-3)
### 3

**Pull request merged**
